idf_component_register(
    SRCS
        "knot_midi_usb_device.c"
    INCLUDE_DIRS
        "."
    REQUIRES
        "knot_midi_translator"
        "knot_midi_uart"
        "knot_midi_queue"
        "knot_usb_mode"
        "tinyusb"
        "grid_common"
        "grid_esp32_led"
        "esp_hw_support"
        "driver"
)
